# Generated by Django 3.2.8 on 2021-10-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanDirectApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='details',
            field=models.CharField(default='', max_length=250, verbose_name='Details'),
            preserve_default=False,
        ),
    ]
