# Generated by Django 3.2.8 on 2021-10-22 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlanDirectApp', '0002_todo_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date_added',
            new_name='start',
        ),
    ]
