# Generated by Django 3.2.8 on 2021-10-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanDirectApp', '0003_rename_date_added_todo_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='start',
            field=models.DateTimeField(verbose_name='Date added'),
        ),
    ]
