# Generated by Django 3.2.8 on 2021-10-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanDirectApp', '0004_alter_todo_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='color',
            field=models.CharField(default='blue', max_length=7, verbose_name='color'),
            preserve_default=False,
        ),
    ]
